### ISSUE TITLE
Option: Surpress All Error Messages

### ISSUE THREAD

**Issue by Drizzard2** [kaminaris/MaxDps#17]
Howdo!

Currently MaxDPS is suffering from an issue where if you have a character like a rogue (during shadowdance or stealth) or a evoker (during soar) that switches the action bar, MaxDps begins spamming you with error messages that you don't have certain abilities on your action bar.

https://i.imgur.com/nFTljgb.png

I have been told on Discord that it's not possible to solve this, so I would like an option in MaxDps that hides ALL error messages. Even if you don't have the ability on your hotbar. That way, you don't get spammed to death when playing rogue or evoker.

**Comment by NickolasJohnson** [comment]
Discord misled you. It takes a bit of effort to get rid of all the annoying messages but if you're looking to get rid of that one specifically you'll need to edit the buttons.lua file located in Interface/Addons/Maxdps on your computer.
It's around line 540. If you search for "Spell not found on action" you'll find it.

I deleted the following code block:
```
	else
		local spellName = GetSpellInfo(spellId);
		self:Print(
			self.Colors.Error ..
			'Spell not found on action bars: ' ..
			(spellName and spellName or 'Unknown') ..
			'(' .. spellId .. ')'
		);
```
that's just the other logic branch for if a spell is missing. Given, if a spell is actually missing it won't tell you once you change this.

If anyone sees this and they're looking to get rid of other annoying messages most of them are in the core.lua file. Search ":Print" and you should find them.
I'm honestly not sure why these messages keep coming back. I had them disabled but it seems like every other update they become undisable-able if that is such a word.

**Comment by doadin** [comment]
I beleive this is no longer an issue with the latest release options for info printed, please reopen this and let me know if there is more I can do to help with this issue.
