### ISSUE TITLE
AddOn Conflict

### ISSUE THREAD

**Issue by Kkthnx** [kaminaris/MaxDps#5]
There seems to be a conflict with an addon. Not too sure what one is causing it. 

https://i.imgur.com/jTd10s2.png

**Comment by Kkthnx** [comment]
I closed this at first because I am unsure if I am causing this or not.

More info.
Playing a BM Hunter. Using the latest version of MaxDps and MaxDps_Hunter. Can not reproduce when I only have these two addons enabled.

As soon as I enabled BetterWardrobe AddOn I was able to reproduce this.

**Comment by pwilkowski** [comment]
This has been resolved in newest release
