### ISSUE TITLE
Config.lua error in some class modules

### ISSUE THREAD

**Issue by kojakk** [kaminaris/MaxDps#9]
Some class modules break due to an error when attempting to add the options menu in the Config.lua. Recommend commenting out so the modules can still function until a fix can be identified.

**Comment by stophman1** [comment]
It can be replace with something like this.
```lua	
local subcategory, layout = Settings.RegisterCanvasLayoutSubcategory(Settings.GetCategory(optionsFrame.parent), optionsFrame, optionsFrame.name);
Settings.RegisterAddOnCategory(subcategory);
```
